/* The following code was generated by JFlex 1.4.3 on 9/19/15 8:47 PM */

package com.powertuple.intellij.haskell;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.powertuple.intellij.haskell.psi.HaskellTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/19/15 8:47 PM from the specification file
 * <tt>/home/rik/idea/intellij-haskell/src/main/scala/com/powertuple/intellij/haskell/_HaskellLexer.flex</tt>
 */
public class _HaskellLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int TEX = 4;
  public static final int NCOMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\1\1\4\0\1\1\3\0\1\1\1\3\1\0\1\1\1\2\21\0"+
    "\1\1\1\4\1\75\1\74\1\5\1\76\1\76\1\45\1\73\1\112"+
    "\1\113\1\76\1\24\1\114\1\37\1\77\1\76\1\27\1\67\1\67"+
    "\1\67\1\67\3\32\2\23\1\106\1\115\1\100\1\102\1\101\1\76"+
    "\1\103\1\57\1\62\1\60\1\26\1\35\1\63\1\72\1\54\1\66"+
    "\1\22\1\61\1\52\1\71\1\50\1\33\1\66\1\56\1\65\1\53"+
    "\1\55\1\51\1\64\1\22\1\31\1\70\1\22\1\116\1\34\1\43"+
    "\1\47\1\44\1\117\1\25\1\41\1\17\1\10\1\11\1\7\1\42"+
    "\1\125\1\6\2\21\1\13\1\123\1\12\1\16\1\121\1\21\1\15"+
    "\1\14\1\120\1\20\1\46\1\124\1\30\1\122\1\21\1\36\1\104"+
    "\1\40\1\105\u2111\0\1\107\1\0\1\110\77\0\1\111\ude2d\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\2\4\1\5\11\6\1\7"+
    "\1\10\1\5\1\10\1\11\1\12\1\5\1\13\1\14"+
    "\1\15\1\5\1\16\1\2\1\17\1\5\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\3\6\4\36\2\1\4\0"+
    "\2\5\1\6\1\37\1\40\3\6\1\41\4\6\1\42"+
    "\2\6\1\7\2\0\1\5\3\0\1\5\3\0\1\43"+
    "\1\44\1\45\1\26\2\0\1\24\1\0\1\46\1\0"+
    "\1\25\1\27\1\47\1\24\1\50\3\0\1\51\2\0"+
    "\4\6\1\52\1\53\1\1\1\0\1\3\6\0\1\54"+
    "\1\55\11\6\1\56\2\6\1\57\1\0\1\57\1\60"+
    "\1\61\3\0\2\62\1\63\1\64\37\0\1\65\1\66"+
    "\1\67\1\70\4\6\2\52\2\53\10\0\6\6\1\71"+
    "\1\72\2\6\1\73\32\0\1\74\1\75\2\6\4\0"+
    "\1\76\6\6\1\77\4\0\1\6\1\100\2\0\1\101"+
    "\1\102\1\6\1\103\4\6\5\0\1\104\1\0\2\6"+
    "\1\105\1\6\1\106\6\0\1\107\1\0\1\110\1\0"+
    "\1\111\25\0\1\112\3\0\1\44\1\0\1\113\2\0"+
    "\1\114\1\115\1\116";

  private static int [] zzUnpackAction() {
    int [] result = new int[324];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\126\0\254\0\u0102\0\u0158\0\u01ae\0\u0102\0\u0204"+
    "\0\u025a\0\u02b0\0\u0306\0\u035c\0\u03b2\0\u0408\0\u045e\0\u04b4"+
    "\0\u050a\0\u0560\0\u05b6\0\u060c\0\u0662\0\u06b8\0\u070e\0\u0764"+
    "\0\u0102\0\u0102\0\u045e\0\u07ba\0\u0810\0\u0866\0\u0102\0\u08bc"+
    "\0\u0912\0\u07ba\0\u0968\0\u07ba\0\u09be\0\u0102\0\u0102\0\u0102"+
    "\0\u0102\0\u0102\0\u0102\0\u0102\0\u0a14\0\u0102\0\u0a6a\0\u0ac0"+
    "\0\u0b16\0\u0102\0\u0b6c\0\u0bc2\0\u0c18\0\u0c6e\0\u0cc4\0\u0d1a"+
    "\0\u0d70\0\u0dc6\0\u0e1c\0\u0e72\0\u0ec8\0\u0f1e\0\u045e\0\u0f74"+
    "\0\u0fca\0\u1020\0\u1076\0\u045e\0\u10cc\0\u1122\0\u1178\0\u11ce"+
    "\0\u045e\0\u1224\0\u127a\0\u12d0\0\u1326\0\u137c\0\u13d2\0\u1428"+
    "\0\u147e\0\u14d4\0\u152a\0\u1580\0\u15d6\0\u162c\0\u1682\0\u16d8"+
    "\0\u0102\0\u07ba\0\u172e\0\u1784\0\u17da\0\u0866\0\u0102\0\u1830"+
    "\0\u07ba\0\u07ba\0\u0102\0\u1886\0\u1886\0\u18dc\0\u1932\0\u1988"+
    "\0\u0102\0\u19de\0\u1a34\0\u1a8a\0\u1ae0\0\u1b36\0\u1b8c\0\u1be2"+
    "\0\u1c38\0\u1c8e\0\u1ce4\0\u1d3a\0\u1d90\0\u1de6\0\u1e3c\0\u1e92"+
    "\0\u1ee8\0\u1f3e\0\u0102\0\u1f94\0\u1fea\0\u2040\0\u2096\0\u20ec"+
    "\0\u2142\0\u2198\0\u21ee\0\u2244\0\u229a\0\u045e\0\u22f0\0\u2346"+
    "\0\u239c\0\u239c\0\u23f2\0\u1428\0\u147e\0\u2448\0\u249e\0\u24f4"+
    "\0\u0102\0\u254a\0\u0102\0\u0102\0\u25a0\0\u25f6\0\u264c\0\u26a2"+
    "\0\u26f8\0\u274e\0\u27a4\0\u27fa\0\u2850\0\u28a6\0\u28fc\0\u2952"+
    "\0\u29a8\0\u29fe\0\u2a54\0\u2aaa\0\u2b00\0\u2b56\0\u2bac\0\u2c02"+
    "\0\u2c58\0\u2cae\0\u2d04\0\u2d5a\0\u2db0\0\u2e06\0\u2e5c\0\u2eb2"+
    "\0\u2f08\0\u2f5e\0\u2fb4\0\u0102\0\u0102\0\u0102\0\u0102\0\u300a"+
    "\0\u3060\0\u30b6\0\u310c\0\u0102\0\u3162\0\u31b8\0\u0102\0\u320e"+
    "\0\u3264\0\u32ba\0\u3310\0\u3366\0\u33bc\0\u3412\0\u3468\0\u34be"+
    "\0\u3514\0\u356a\0\u35c0\0\u3616\0\u366c\0\u045e\0\u045e\0\u36c2"+
    "\0\u3718\0\u045e\0\u376e\0\u37c4\0\u381a\0\u3870\0\u38c6\0\u391c"+
    "\0\u3972\0\u39c8\0\u3a1e\0\u3a74\0\u3aca\0\u3b20\0\u3b76\0\u3bcc"+
    "\0\u3c22\0\u3c78\0\u3cce\0\u3d24\0\u3d7a\0\u3dd0\0\u3e26\0\u3e7c"+
    "\0\u3ed2\0\u3f28\0\u3f7e\0\u3fd4\0\u402a\0\u045e\0\u4080\0\u40d6"+
    "\0\u412c\0\u4182\0\u41d8\0\u422e\0\u4284\0\u42da\0\u4330\0\u4386"+
    "\0\u43dc\0\u4432\0\u4488\0\u045e\0\u44de\0\u4534\0\u458a\0\u45e0"+
    "\0\u4636\0\u045e\0\u468c\0\u46e2\0\u045e\0\u045e\0\u4738\0\u045e"+
    "\0\u478e\0\u47e4\0\u483a\0\u4890\0\u48e6\0\u493c\0\u4992\0\u49e8"+
    "\0\u4a3e\0\u045e\0\u4a94\0\u4aea\0\u4b40\0\u045e\0\u4b96\0\u045e"+
    "\0\u4bec\0\u4c42\0\u4c98\0\u4cee\0\u4d44\0\u4d9a\0\u045e\0\u4df0"+
    "\0\u045e\0\u4e46\0\u0102\0\u4e9c\0\u4ef2\0\u4f48\0\u4f9e\0\u4ff4"+
    "\0\u504a\0\u50a0\0\u50f6\0\u514c\0\u51a2\0\u51f8\0\u524e\0\u52a4"+
    "\0\u52fa\0\u5350\0\u53a6\0\u53fc\0\u5452\0\u54a8\0\u54fe\0\u5554"+
    "\0\u0102\0\u55aa\0\u5600\0\u5656\0\u0102\0\u56ac\0\u0102\0\u5702"+
    "\0\u5758\0\u0102\0\u0102\0\u0102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[324];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\5\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\2\17\1\20\1\21\2\17"+
    "\1\22\1\23\1\24\1\17\1\22\1\25\1\17\1\22"+
    "\1\23\1\22\1\26\1\22\1\27\1\30\1\31\2\17"+
    "\1\32\1\33\1\34\1\17\1\34\17\22\1\23\3\22"+
    "\1\35\1\36\2\34\1\37\1\40\1\34\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\2\17\1\60\1\61"+
    "\1\17\2\62\1\63\33\62\1\64\1\65\66\62\34\66"+
    "\1\67\71\66\127\0\1\5\2\0\1\5\124\0\1\7"+
    "\127\0\1\34\1\70\1\0\1\71\1\72\6\0\1\73"+
    "\3\0\1\34\7\0\1\34\2\0\1\74\5\0\1\34"+
    "\1\0\1\34\25\0\1\75\11\34\24\0\1\76\1\17"+
    "\1\77\2\17\1\100\11\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\3\17\1\101\2\17\5\0\1\76\10\17\1\102"+
    "\5\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\3\17\1\103\4\17\1\104\5\17\1\0\1\105"+
    "\6\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\5\17"+
    "\1\106\10\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\6\17"+
    "\5\0\1\76\3\17\1\107\12\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\6\17\5\0\1\76\3\17\1\110\12\17"+
    "\1\0\7\17\1\0\1\17\3\0\2\17\1\0\1\17"+
    "\1\0\1\17\1\0\24\17\24\0\6\17\5\0\1\76"+
    "\16\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\1\17\1\111\14\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\5\0\1\76\5\17\1\112\10\17\1\0"+
    "\1\113\6\17\1\0\1\17\3\0\2\17\1\0\1\17"+
    "\1\0\1\17\1\0\24\17\24\0\6\17\5\0\1\114"+
    "\16\22\1\0\7\22\1\0\1\22\3\0\2\22\1\0"+
    "\1\22\1\0\1\22\1\0\24\22\24\0\6\22\11\0"+
    "\1\115\11\0\1\23\3\0\1\23\2\0\1\23\1\0"+
    "\1\116\1\115\31\0\1\23\43\0\1\34\15\0\1\23"+
    "\1\34\2\0\1\23\2\0\1\23\1\0\1\117\2\0"+
    "\1\34\5\0\1\34\1\0\1\34\17\0\1\23\5\0"+
    "\12\34\30\0\1\115\4\0\1\120\4\0\1\23\3\0"+
    "\1\23\2\121\1\23\1\120\1\116\1\115\31\0\1\23"+
    "\36\0\3\122\1\0\1\122\1\123\3\122\1\124\2\122"+
    "\1\125\7\122\1\123\7\122\1\123\2\122\1\123\1\122"+
    "\1\126\3\122\1\123\1\122\1\123\25\122\12\123\17\122"+
    "\37\0\1\127\73\0\1\34\15\0\1\23\1\34\2\0"+
    "\1\23\2\0\1\23\1\0\1\117\2\0\1\130\1\131"+
    "\4\0\1\34\1\0\1\34\17\0\1\23\5\0\4\34"+
    "\1\132\5\34\24\0\1\34\16\0\1\34\7\0\1\34"+
    "\2\0\1\34\5\0\1\34\1\0\1\34\25\0\12\34"+
    "\17\0\3\133\1\0\30\133\1\134\36\133\1\0\12\133"+
    "\1\135\17\133\3\136\1\137\30\136\1\140\37\136\1\137"+
    "\31\136\5\0\1\34\16\0\1\34\7\0\1\34\2\0"+
    "\1\141\5\0\1\34\1\0\1\34\25\0\12\34\24\0"+
    "\1\34\16\0\1\34\7\0\1\34\2\0\1\34\5\0"+
    "\1\34\1\0\1\34\25\0\4\34\1\142\5\34\24\0"+
    "\1\34\16\0\1\34\7\0\1\34\2\0\1\34\3\0"+
    "\1\143\1\0\1\34\1\0\1\34\25\0\12\34\24\0"+
    "\1\144\16\0\1\144\7\0\1\144\2\0\1\144\5\0"+
    "\1\144\1\0\1\144\25\0\11\144\1\145\25\0\2\146"+
    "\1\147\1\150\10\146\3\0\1\146\2\0\1\146\10\0"+
    "\2\146\1\0\1\146\1\0\1\146\35\0\1\151\13\0"+
    "\1\152\1\153\4\146\5\0\1\76\16\17\1\0\7\17"+
    "\1\0\1\17\3\0\2\17\1\0\1\17\1\0\1\17"+
    "\1\0\24\17\24\0\2\17\1\154\2\17\1\155\5\0"+
    "\1\76\10\17\1\156\5\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\5\0\1\76\16\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\5\17\1\157\3\0\1\62\161\0\1\160"+
    "\126\0\1\161\65\0\34\66\1\0\71\66\34\0\1\162"+
    "\4\0\1\163\73\0\1\164\2\0\1\165\124\0\1\166"+
    "\126\0\1\167\1\170\1\0\1\171\122\0\1\172\120\0"+
    "\1\34\16\0\1\34\7\0\1\34\2\0\1\34\1\173"+
    "\4\0\1\34\1\0\1\34\25\0\12\34\17\0\2\174"+
    "\2\0\1\174\1\75\16\174\1\75\7\174\1\75\2\174"+
    "\1\75\5\174\1\75\1\174\1\75\25\174\12\75\17\174"+
    "\5\0\1\76\125\0\1\76\1\17\1\175\4\17\1\176"+
    "\7\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\16\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\1\17"+
    "\1\177\4\17\5\0\1\76\7\17\1\200\6\17\1\0"+
    "\7\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\1\17"+
    "\1\201\5\17\1\202\6\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\5\0\1\76\16\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\1\203\5\17\5\0\1\76\6\17\1\204"+
    "\7\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\16\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\4\17"+
    "\1\205\1\17\5\0\1\76\16\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\1\206\5\17\5\0\1\76\16\17\1\0"+
    "\1\207\6\17\1\0\1\17\3\0\2\17\1\0\1\17"+
    "\1\0\1\17\1\0\24\17\24\0\6\17\5\0\1\76"+
    "\6\17\1\210\7\17\1\0\7\17\1\0\1\17\3\0"+
    "\2\17\1\0\1\17\1\0\1\17\1\0\24\17\24\0"+
    "\6\17\5\0\1\114\143\0\1\211\1\212\2\0\1\211"+
    "\2\0\1\211\4\0\1\212\27\0\1\211\36\0\3\213"+
    "\1\0\122\213\3\122\1\0\1\122\1\123\16\122\1\123"+
    "\7\122\1\123\2\122\1\123\5\122\1\123\1\122\1\123"+
    "\25\122\12\123\17\122\27\0\1\214\2\0\1\214\34\0"+
    "\1\214\45\0\3\215\5\0\1\215\3\0\1\215\1\0"+
    "\3\215\2\0\1\215\2\0\1\215\3\0\1\215\15\0"+
    "\2\215\1\0\2\215\3\0\1\215\61\0\1\213\3\0"+
    "\1\213\2\0\1\213\34\0\1\213\43\0\1\34\15\0"+
    "\1\213\1\34\2\0\1\213\2\0\1\213\1\0\1\34"+
    "\2\0\1\34\5\0\1\34\1\0\1\34\17\0\1\213"+
    "\5\0\12\34\31\0\1\216\10\0\1\213\3\0\1\213"+
    "\2\0\1\213\34\0\1\213\47\0\1\217\11\0\1\213"+
    "\3\0\1\213\2\0\1\213\34\0\1\213\47\0\1\220"+
    "\11\0\1\213\3\0\1\213\2\0\1\213\34\0\1\213"+
    "\37\0\1\221\1\222\2\221\1\223\16\221\1\0\7\221"+
    "\1\0\1\221\1\0\1\221\1\0\2\221\1\0\1\221"+
    "\1\0\1\221\1\0\23\221\11\0\1\221\13\0\6\221"+
    "\2\130\2\0\122\130\73\0\1\224\41\0\1\133\2\0"+
    "\1\133\2\0\1\133\1\225\4\0\1\226\1\0\1\133"+
    "\1\227\1\226\1\230\1\0\1\226\1\0\1\133\1\231"+
    "\3\0\1\133\3\0\2\133\1\232\1\233\1\234\1\235"+
    "\1\236\1\237\2\0\1\240\1\241\1\0\1\242\1\243"+
    "\1\237\1\234\1\0\1\226\2\0\1\234\2\133\23\0"+
    "\1\133\12\0\1\144\16\0\1\144\7\0\1\144\2\0"+
    "\1\144\5\0\1\144\1\0\1\144\23\0\1\224\1\0"+
    "\12\144\20\0\4\244\2\0\1\136\2\0\1\136\2\0"+
    "\1\136\1\245\4\0\1\136\1\0\1\136\1\246\1\136"+
    "\1\247\1\0\1\136\1\0\1\136\1\250\3\0\1\136"+
    "\3\0\2\136\1\251\1\252\1\253\1\254\1\255\1\256"+
    "\2\0\1\257\1\260\1\0\1\261\1\262\1\256\1\253"+
    "\1\0\1\136\2\0\1\253\2\136\23\0\1\136\12\0"+
    "\1\144\16\0\1\144\7\0\1\144\2\0\1\144\5\0"+
    "\1\144\1\0\1\144\25\0\12\144\24\0\1\263\16\146"+
    "\1\0\7\146\1\0\1\146\3\0\2\146\1\0\1\146"+
    "\1\0\1\146\1\0\24\146\10\0\1\264\13\0\6\146"+
    "\5\0\1\263\16\146\1\0\7\146\1\0\1\146\3\0"+
    "\2\146\1\0\1\146\1\0\1\146\1\0\24\146\10\0"+
    "\1\265\13\0\6\146\5\0\1\263\16\146\1\0\7\146"+
    "\1\0\1\146\3\0\2\146\1\0\1\146\1\0\1\146"+
    "\1\0\24\146\10\0\1\151\13\0\6\146\5\0\1\263"+
    "\16\146\1\0\7\146\1\0\1\146\3\0\2\146\1\0"+
    "\1\146\1\0\1\146\1\0\24\146\10\0\1\266\13\0"+
    "\6\146\5\0\1\263\16\146\1\0\7\146\1\0\1\146"+
    "\3\0\2\146\1\0\1\146\1\0\1\146\1\0\24\146"+
    "\10\0\1\267\13\0\6\146\5\0\1\76\16\17\1\0"+
    "\7\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\1\17\1\270\4\17\5\0"+
    "\1\76\3\17\1\271\12\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\5\0\1\76\2\17\1\272\13\17\1\0"+
    "\7\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\3\17"+
    "\1\273\12\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\6\17"+
    "\1\0\1\274\1\275\2\274\1\0\16\274\1\0\7\274"+
    "\1\0\1\274\1\0\1\274\1\0\2\274\1\0\1\274"+
    "\1\0\1\274\1\0\23\274\11\0\1\274\13\0\6\274"+
    "\2\0\1\276\1\277\156\0\1\162\102\0\1\300\114\0"+
    "\2\164\2\0\122\164\17\0\1\301\115\0\1\302\126\0"+
    "\1\303\123\0\1\304\5\0\1\305\126\0\1\306\120\0"+
    "\1\307\115\0\2\174\2\0\122\174\5\0\1\76\1\310"+
    "\15\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\16\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\1\311"+
    "\5\17\5\0\1\76\10\17\1\312\5\17\1\0\7\17"+
    "\1\0\1\17\3\0\2\17\1\0\1\17\1\0\1\17"+
    "\1\0\24\17\24\0\6\17\5\0\1\76\3\17\1\313"+
    "\12\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\16\17\1\0\1\314\6\17\1\0\1\17\3\0"+
    "\2\17\1\0\1\17\1\0\1\17\1\0\24\17\24\0"+
    "\6\17\5\0\1\76\1\315\15\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\6\17\5\0\1\76\16\17\1\0\1\316"+
    "\6\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\3\17"+
    "\1\317\12\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\6\17"+
    "\5\0\1\76\16\17\1\0\7\17\1\0\1\17\3\0"+
    "\2\17\1\0\1\17\1\0\1\17\1\0\24\17\24\0"+
    "\1\320\5\17\5\0\1\76\6\17\1\321\7\17\1\0"+
    "\7\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\3\17"+
    "\1\322\12\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\6\17"+
    "\23\0\1\211\3\0\1\211\2\0\1\211\34\0\1\211"+
    "\47\0\1\115\11\0\1\213\3\0\1\213\2\0\1\213"+
    "\2\0\1\115\31\0\1\213\46\0\1\323\134\0\1\324"+
    "\150\0\1\325\66\0\1\221\151\0\1\326\2\0\1\326"+
    "\34\0\1\326\61\0\1\226\3\0\1\226\2\0\1\226"+
    "\34\0\1\226\3\0\1\224\67\0\1\327\14\0\1\330"+
    "\5\0\1\331\54\0\3\332\5\0\1\332\3\0\1\332"+
    "\1\0\3\332\2\0\1\332\2\0\1\332\3\0\1\332"+
    "\15\0\2\332\1\0\2\332\3\0\1\332\71\0\1\237"+
    "\14\0\1\333\2\0\1\334\1\0\1\335\13\0\1\133"+
    "\56\0\1\133\3\0\1\133\2\0\1\133\1\0\3\133"+
    "\5\0\2\133\2\0\20\133\1\0\3\133\10\0\1\133"+
    "\12\0\1\133\60\0\1\327\5\0\1\336\121\0\1\133"+
    "\135\0\1\133\75\0\1\337\15\0\1\340\3\0\1\341"+
    "\10\0\1\133\1\0\1\342\112\0\1\133\130\0\1\336"+
    "\124\0\1\342\5\0\1\133\75\0\1\327\15\0\1\133"+
    "\125\0\1\133\7\0\1\133\43\0\4\244\27\0\1\136"+
    "\120\0\1\136\2\0\1\136\34\0\1\136\73\0\1\343"+
    "\14\0\1\344\5\0\1\345\54\0\3\136\5\0\1\136"+
    "\3\0\1\136\1\0\3\136\2\0\1\136\2\0\1\136"+
    "\3\0\1\136\15\0\2\136\1\0\2\136\3\0\1\136"+
    "\71\0\1\256\14\0\1\346\2\0\1\347\1\0\1\350"+
    "\13\0\1\136\56\0\1\136\3\0\1\136\2\0\1\136"+
    "\1\0\3\136\5\0\2\136\2\0\20\136\1\0\3\136"+
    "\10\0\1\136\12\0\1\136\60\0\1\343\5\0\1\351"+
    "\121\0\1\136\135\0\1\136\75\0\1\136\15\0\1\352"+
    "\3\0\1\353\10\0\1\136\1\0\1\354\112\0\1\136"+
    "\130\0\1\351\124\0\1\354\5\0\1\136\75\0\1\343"+
    "\15\0\1\136\125\0\1\136\7\0\1\136\47\0\1\263"+
    "\76\0\1\264\26\0\1\76\3\17\1\355\12\17\1\0"+
    "\7\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\4\17"+
    "\1\356\11\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\17\1\0\24\17\24\0\6\17"+
    "\5\0\1\76\12\17\1\357\3\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\6\17\5\0\1\76\7\17\1\360\6\17"+
    "\1\0\7\17\1\0\1\17\3\0\2\17\1\0\1\17"+
    "\1\0\1\17\1\0\24\17\24\0\6\17\3\0\1\274"+
    "\125\0\1\277\164\0\1\361\76\0\1\362\120\0\1\363"+
    "\125\0\1\304\126\0\1\164\127\0\1\164\132\0\1\364"+
    "\120\0\1\304\121\0\1\76\16\17\1\0\3\17\1\365"+
    "\3\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\16\17"+
    "\1\0\1\366\6\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\7\17\1\367\6\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\5\0\1\76\1\370\15\17\1\0\7\17"+
    "\1\0\1\17\3\0\2\17\1\0\1\17\1\0\1\17"+
    "\1\0\24\17\24\0\6\17\5\0\1\76\12\17\1\371"+
    "\3\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\16\17\1\0\7\17\1\0\1\17\3\0\2\17"+
    "\1\0\1\17\1\0\1\372\1\0\24\17\24\0\6\17"+
    "\5\0\1\76\16\17\1\0\7\17\1\0\1\17\3\0"+
    "\2\17\1\0\1\17\1\0\1\17\1\0\24\17\24\0"+
    "\2\17\1\373\3\17\5\0\1\76\6\17\1\374\7\17"+
    "\1\0\7\17\1\0\1\17\3\0\2\17\1\0\1\17"+
    "\1\0\1\17\1\0\24\17\24\0\6\17\36\0\1\375"+
    "\207\0\1\376\13\0\1\377\146\0\1\326\2\0\1\326"+
    "\34\0\1\326\3\0\1\224\104\0\1\133\110\0\1\133"+
    "\157\0\1\133\45\0\3\332\5\0\1\332\3\0\1\332"+
    "\1\0\3\332\2\0\1\332\2\0\1\332\3\0\1\332"+
    "\15\0\2\332\1\0\2\332\3\0\1\332\3\0\1\224"+
    "\110\0\1\133\127\0\1\133\76\0\1\133\30\0\1\133"+
    "\124\0\1\133\120\0\1\133\16\0\1\224\114\0\1\133"+
    "\74\0\1\133\144\0\1\133\127\0\1\136\110\0\1\136"+
    "\157\0\1\136\114\0\1\136\127\0\1\136\76\0\1\136"+
    "\30\0\1\136\124\0\1\136\126\0\1\136\74\0\1\136"+
    "\144\0\1\136\61\0\1\u0100\1\76\16\17\1\0\7\17"+
    "\1\0\1\17\3\0\2\17\1\0\1\17\1\0\1\17"+
    "\1\0\24\17\24\0\6\17\5\0\1\76\5\17\1\u0101"+
    "\10\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\3\17\1\u0102\12\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\6\0\1\u0103\137\0\1\u0104\117\0\1\305"+
    "\130\0\1\164\115\0\1\76\5\17\1\u0105\1\17\1\u0106"+
    "\6\17\1\0\7\17\1\0\1\17\3\0\2\17\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\5\0"+
    "\1\76\4\17\1\u0107\11\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\5\0\1\76\16\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\1\u0108\5\17\5\0\1\76\16\17\1\0"+
    "\7\17\1\0\1\17\3\0\1\17\1\u0109\1\0\1\17"+
    "\1\0\1\17\1\0\24\17\24\0\6\17\5\0\1\76"+
    "\5\17\1\u010a\10\17\1\0\7\17\1\0\1\17\3\0"+
    "\2\17\1\0\1\17\1\0\1\17\1\0\24\17\24\0"+
    "\6\17\5\0\1\76\1\u010b\15\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\6\17\5\0\1\76\16\17\1\0\7\17"+
    "\1\0\1\17\3\0\2\17\1\0\1\17\1\0\1\17"+
    "\1\0\24\17\24\0\1\17\1\u010c\4\17\17\0\1\u010d"+
    "\114\0\1\u010e\131\0\1\u010f\121\0\1\u0110\1\u0111\123\0"+
    "\1\76\3\17\1\u0112\12\17\1\0\7\17\1\0\1\17"+
    "\3\0\2\17\1\0\1\17\1\0\1\17\1\0\24\17"+
    "\24\0\6\17\12\0\1\u0113\123\0\1\305\122\0\1\76"+
    "\11\17\1\u0114\4\17\1\0\7\17\1\0\1\17\3\0"+
    "\2\17\1\0\1\17\1\0\1\17\1\0\24\17\24\0"+
    "\6\17\5\0\1\76\4\17\1\u0115\11\17\1\0\7\17"+
    "\1\0\1\17\3\0\2\17\1\0\1\17\1\0\1\17"+
    "\1\0\24\17\24\0\6\17\5\0\1\76\16\17\1\0"+
    "\7\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\1\u0116\5\17\5\0\1\76"+
    "\4\17\1\u0117\11\17\1\0\7\17\1\0\1\17\3\0"+
    "\2\17\1\0\1\17\1\0\1\17\1\0\24\17\24\0"+
    "\6\17\5\0\1\76\3\17\1\u0118\12\17\1\0\7\17"+
    "\1\0\1\17\3\0\2\17\1\0\1\17\1\0\1\17"+
    "\1\0\24\17\24\0\6\17\16\0\1\u0119\125\0\1\u011a"+
    "\145\0\1\u011b\101\0\1\u011c\140\0\1\u011d\136\0\1\u011e"+
    "\74\0\1\76\3\17\1\u011f\12\17\1\0\7\17\1\0"+
    "\1\17\3\0\2\17\1\0\1\17\1\0\1\17\1\0"+
    "\24\17\24\0\6\17\4\0\1\u0120\1\76\16\17\1\0"+
    "\7\17\1\0\1\17\3\0\2\17\1\0\1\17\1\0"+
    "\1\17\1\0\24\17\24\0\6\17\5\0\1\76\16\17"+
    "\1\0\7\17\1\0\1\17\3\0\1\17\1\u0121\1\0"+
    "\1\17\1\0\1\17\1\0\24\17\24\0\6\17\10\0"+
    "\1\u0122\127\0\1\u0123\132\0\1\u0124\122\0\1\u0125\234\0"+
    "\1\u0126\21\0\1\u0127\114\0\1\u0128\2\0\1\u0129\125\0"+
    "\1\u012a\132\0\1\u012b\227\0\1\u012c\13\0\1\u012d\135\0"+
    "\1\u012e\232\0\1\u012f\32\0\1\u0130\135\0\1\u0123\75\0"+
    "\1\u0131\142\0\1\u0132\113\0\1\u0133\122\0\1\u0134\236\0"+
    "\1\u0135\125\0\1\u0136\15\0\1\u0137\126\0\1\u0138\235\0"+
    "\1\u0139\14\0\1\u013a\132\0\1\u013b\125\0\1\u013c\147\0"+
    "\1\u013d\104\0\1\u013e\146\0\1\u013f\102\0\1\u0140\125\0"+
    "\1\u0141\121\0\1\u0142\234\0\1\u0143\125\0\1\u0144\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[22446];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\2\1\1\11\21\1\2\11\4\1"+
    "\1\11\6\1\7\11\1\1\1\11\3\1\1\11\5\1"+
    "\4\0\21\1\2\0\1\1\3\0\1\1\3\0\2\1"+
    "\1\11\1\1\2\0\1\1\1\0\1\11\1\0\2\1"+
    "\1\11\2\1\3\0\1\11\2\0\7\1\1\0\1\1"+
    "\6\0\1\11\16\1\1\0\3\1\3\0\1\11\1\1"+
    "\2\11\37\0\4\11\4\1\1\11\2\1\1\11\10\0"+
    "\13\1\32\0\4\1\4\0\10\1\4\0\2\1\2\0"+
    "\10\1\5\0\1\1\1\0\5\1\6\0\1\1\1\0"+
    "\1\1\1\0\1\11\25\0\1\11\3\0\1\11\1\0"+
    "\1\11\2\0\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[324];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _HaskellLexer() {
    this((java.io.Reader)null);
  }
    private int commentStart;
    private int commentDepth;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _HaskellLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 218) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 59: 
          { return HS_CASE;
          }
        case 79: break;
        case 49: 
          { return HS_HEXADECIMAL;
          }
        case 80: break;
        case 36: 
          { return HS_COMMENT;
          }
        case 81: break;
        case 40: 
          { return HS_COLON_COLON;
          }
        case 82: break;
        case 63: 
          { return HS_CLASS;
          }
        case 83: break;
        case 70: 
          { return HS_NEWTYPE;
          }
        case 84: break;
        case 41: 
          { return HS_QUASI_QUOTE_E_START;
          }
        case 85: break;
        case 44: 
          { return HS_PRAGMA_END;
          }
        case 86: break;
        case 6: 
          { return HS_VARID_ID;
          }
        case 87: break;
        case 17: 
          { return HS_AT;
          }
        case 88: break;
        case 45: 
          { return HS_SHEBANG_LINE;
          }
        case 89: break;
        case 31: 
          { return HS_IF;
          }
        case 90: break;
        case 39: 
          { return HS_QUASI_QUOTE_END;
          }
        case 91: break;
        case 14: 
          { return HS_QUOTE;
          }
        case 92: break;
        case 74: 
          { return HS_TYPE_FAMILY;
          }
        case 93: break;
        case 56: 
          { return HS_QUASI_QUOTE_P_START;
          }
        case 94: break;
        case 50: 
          { yybegin(NCOMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
          }
        case 95: break;
        case 4: 
          { return HS_NEWLINE;
          }
        case 96: break;
        case 27: 
          { return HS_SEMICOLON;
          }
        case 97: break;
        case 62: 
          { return HS_INFIX;
          }
        case 98: break;
        case 3: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 99: break;
        case 20: 
          { return HS_CONSYM_ID;
          }
        case 100: break;
        case 47: 
          { return HS_FLOAT;
          }
        case 101: break;
        case 25: 
          { return HS_RIGHT_PAREN;
          }
        case 102: break;
        case 1: 
          { return HS_NCOMMENT;
          }
        case 103: break;
        case 19: 
          { return HS_TILDE;
          }
        case 104: break;
        case 73: 
          { yybegin(TEX); return HS_NCOMMENT;
          }
        case 105: break;
        case 8: 
          { return HS_DECIMAL;
          }
        case 106: break;
        case 43: 
          { if (commentDepth > 0) {
            commentDepth--;
        }
        else {
             int state = yystate();
             yybegin(YYINITIAL);
             zzStartRead = commentStart;
             return HS_NCOMMENT;
        }
          }
        case 107: break;
        case 46: 
          { return HS_LET;
          }
        case 108: break;
        case 64: 
          { return HS_WHERE;
          }
        case 109: break;
        case 7: 
          { return HS_CONID_ID;
          }
        case 110: break;
        case 38: 
          { return HS_STRING_LITERAL;
          }
        case 111: break;
        case 21: 
          { return HS_LEFT_ARROW;
          }
        case 112: break;
        case 68: 
          { return HS_MODULE;
          }
        case 113: break;
        case 10: 
          { return HS_LEFT_BRACE;
          }
        case 114: break;
        case 57: 
          { return HS_DATA;
          }
        case 115: break;
        case 52: 
          { return HS_CHARACTER_LITERAL;
          }
        case 116: break;
        case 51: 
          { return HS_PRAGMA_START;
          }
        case 117: break;
        case 13: 
          { return HS_UNDERSCORE;
          }
        case 118: break;
        case 37: 
          { return HS_NCOMMENT_END;
          }
        case 119: break;
        case 77: 
          { return HS_FOREIGN_IMPORT;
          }
        case 120: break;
        case 54: 
          { return HS_QUASI_QUOTE_D_START;
          }
        case 121: break;
        case 18: 
          { return HS_VERTICAL_BAR;
          }
        case 122: break;
        case 60: 
          { return HS_TYPE;
          }
        case 123: break;
        case 5: 
          { return HS_VARSYM_ID;
          }
        case 124: break;
        case 16: 
          { return HS_EQUAL;
          }
        case 125: break;
        case 35: 
          { return HS_NCOMMENT_START;
          }
        case 126: break;
        case 71: 
          { return HS_INSTANCE;
          }
        case 127: break;
        case 12: 
          { return HS_RIGHT_BRACKET;
          }
        case 128: break;
        case 24: 
          { return HS_LEFT_PAREN;
          }
        case 129: break;
        case 29: 
          { return HS_BACKQUOTE;
          }
        case 130: break;
        case 28: 
          { return HS_LEFT_BRACKET;
          }
        case 131: break;
        case 65: 
          { return HS_INFIXL;
          }
        case 132: break;
        case 67: 
          { return HS_IMPORT;
          }
        case 133: break;
        case 72: 
          { return HS_DERIVING;
          }
        case 134: break;
        case 33: 
          { return HS_DO;
          }
        case 135: break;
        case 15: 
          { return HS_DOT;
          }
        case 136: break;
        case 32: 
          { return HS_IN;
          }
        case 137: break;
        case 48: 
          { return HS_OCTAL;
          }
        case 138: break;
        case 66: 
          { return HS_INFIXR;
          }
        case 139: break;
        case 76: 
          { return HS_TYPE_INSTANCE;
          }
        case 140: break;
        case 42: 
          { commentDepth++;
          }
        case 141: break;
        case 2: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 142: break;
        case 69: 
          { return HS_DEFAULT;
          }
        case 143: break;
        case 23: 
          { return HS_DOUBLE_RIGHT_ARROW;
          }
        case 144: break;
        case 58: 
          { return HS_ELSE;
          }
        case 145: break;
        case 26: 
          { return HS_COMMA;
          }
        case 146: break;
        case 9: 
          { return HS_BACKSLASH;
          }
        case 147: break;
        case 34: 
          { return HS_OF;
          }
        case 148: break;
        case 61: 
          { return HS_THEN;
          }
        case 149: break;
        case 22: 
          { return HS_RIGHT_ARROW;
          }
        case 150: break;
        case 11: 
          { return HS_RIGHT_BRACE;
          }
        case 151: break;
        case 55: 
          { return HS_QUASI_QUOTE_T_START;
          }
        case 152: break;
        case 53: 
          { return HS_QUASI_QUOTE_V_START;
          }
        case 153: break;
        case 78: 
          { return HS_FOREIGN_EXPORT;
          }
        case 154: break;
        case 75: 
          { yybegin(YYINITIAL); return HS_NCOMMENT;
          }
        case 155: break;
        case 30: 
          { 
          }
        case 156: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case NCOMMENT: {
              int state = yystate();
        yybegin(YYINITIAL);
        zzStartRead = commentStart;
        return HS_NCOMMENT;
            }
            case 325: break;
            default:
            return null;
            }
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
